# Generated by Django 3.2 on 2021-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Item_jason', models.CharField(max_length=400)),
                ('District', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('Update_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.IntegerField(default='')),
                ('Update_desc', models.CharField(max_length=500)),
                ('TimeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='shop/image')),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
