# Generated by Django 3.2 on 2021-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/image')),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
