# Generated by Django 3.2 on 2021-04-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_jason',
            new_name='Item_jason',
        ),
    ]
