# Generated by Django 3.2 on 2021-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_id_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('District', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
