# Generated by Django 3.2 on 2021-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_item_jason_order_item_jason'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('Update_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.IntegerField()),
                ('Update_desc', models.CharField(max_length=500)),
                ('TimeStamp', models.DateTimeField()),
            ],
        ),
    ]
